# -*- coding: utf-8 -*-
"""Linh_Caro.gamevui.com.vn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/160SfcvkaY--GvC-sw-n5zzhrKFUT2f3A
"""

board=[" "," "," "," "," "," "," "," "," "]

def print_caro (x1,x2,x3) :
  print("|",board[x1],"|",board[x2],"|",board[x3],"|")
  print(".............")

def show():
  print_caro(0,1,2)
  print_caro(3,4,5)
  print_caro(6,7,8)

def empty_blank():
  for x in range(1,10):
    if board[x-1]==" ":
      return True
  return False

def check_line(ch,x1,x2,x3):
  if board[x1]==ch and board[x2]==ch and board[x3]==ch :
    return True
  return False

def check_win(ch):
  if check_line(ch,0,1,2) or check_line(ch,3,4,5) or check_line(ch,6,7,8):
    return True
  if check_line(ch,0,3,6) or check_line(ch,1,4,7) or check_line(ch,2,5,8):
    return True
  if check_line(ch,0,4,8) or check_line(ch,2,4,6):
    return True

def check(x):
  if x<1 or x>9:
    return False
  else :
    if board[x-1]=="X" or board[x-1]=="O" :
      return False
    else:
      return True

#X thang win =0 va O thang win=1 hoa thi win=2 (random X hoac O danh truoc). Gia su ban dau hoa
from random import randint
win=2
win=randint(0,1)

def game_caro(ch1,ch2):
  global board
  show()
  global win
  while empty_blank():
    print(ch1,"turn: ")
    you =input()
    you=int(you)
    if check(you)==False :
      print("Re-enter")
      continue
    else :
      board[you-1]=ch1
      show()
      if check_win(ch1):
        win=0
        break
      else:
        computer=-1
        while empty_blank():
          print(ch2,"turn: ")
          computer= input()
          computer=int(computer)
          if check(computer) ==False:
            print("Re-enter")
            continue
          else:
            board[computer-1]=ch2
            show()
            break
        if check_win(ch2):
              win =1
              break
  if check_win(ch1):
    win=0
    print(ch1," win")
  elif check_win(ch2):
    win=1
    print(ch2,"win")
  else :
    win=2
    win=randint(0,1)
    print("Tie")
  for x in range(0,9):
    board[x]=" "

ch1="X"
ch2="O"
if win==1:
  ch1="O"
  ch2="X"

game_caro(ch1,ch2)